# Generated by Django 2.1.7 on 2019-03-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('special', models.CharField(max_length=30, verbose_name='商品规格')),
                ('picture', models.ImageField(upload_to='static/upload/good')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='类型')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goodtype', verbose_name='图片')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'db_table': 'goodtype',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.GoodType', verbose_name='商品类型'),
        ),
    ]
