# Generated by Django 2.1.7 on 2019-03-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190330_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'good'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'verbose_name': 'goodtype'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
    ]
